name: Build wow-amd64

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出源码
        uses: actions/checkout@v5

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: 设置 Go 环境
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: 修改 package.json 版本号（追加 commit 哈希）
        run: |
          HASH=$(git rev-parse --short HEAD)
          VERSION=$(jq -r '.version' web/package.json)
          NEW_VERSION="${VERSION}~${HASH}"
          jq --arg new "$NEW_VERSION" '.version = $new' web/package.json > web/package.json.tmp && mv web/package.json.tmp web/package.json
          echo "新版本号: $NEW_VERSION"

      - name: 构建前端 (web)
        working-directory: ./web
        run: |
          npm ci
          npm run build

      - name: 构建 Go 后端（amd64）
        run: |
          GOOS=linux GOARCH=amd64 go build -tags vue -ldflags="-s -w" -o wow
 
      - name: 上传 wow 二进制作为 Artifact
        uses: actions/upload-artifact@v6
        with:
          name: wow
          path: wow
